from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import numpy as np
import pandas as pd

from .config import Settings
from .costs import execution_cost_breakdown


@dataclass(frozen=True)
class FeatureSet:
    frame: pd.DataFrame
    feature_columns: list[str]
    horizons: list[int]


def build_feature_set(
    candles: pd.DataFrame,
    news: pd.DataFrame,
    settings: Settings,
    include_labels: bool = True,
) -> FeatureSet:
    """Build leakage-safe hourly features and independent market-event labels.

    Version 2 intentionally does not use EMA20/EMA50 crossovers as the event source.
    A market event is generated by one of four structures: Donchian breakout,
    volatility-squeeze release, trend pullback resumption, or directional impulse.
    """
    if candles.empty:
        raise ValueError("No candles available")

    cfg = settings.section("features")
    model_cfg = settings.section("model")
    strategy_cfg = settings.section("strategy")
    horizons = [int(h) for h in model_cfg.get("horizons_hours", [1, 2, 3])]

    frame = candles.copy().sort_values("open_time").drop_duplicates("open_time").reset_index(drop=True)
    frame["open_time"] = pd.to_datetime(frame["open_time"], utc=True)
    for col in ("open", "high", "low", "close", "volume", "quote_volume", "trades"):
        if col in frame:
            frame[col] = pd.to_numeric(frame[col], errors="coerce")

    close = frame["close"]
    high = frame["high"]
    low = frame["low"]
    open_ = frame["open"]

    # --- Adaptive trend and volatility structure ---
    kama_er = int(cfg.get("kama_er_period", 10))
    kama_fast = int(cfg.get("kama_fast_period", 2))
    kama_slow = int(cfg.get("kama_slow_period", 30))
    frame["kama"] = _kama(close, kama_er, kama_fast, kama_slow)
    frame["kama_slope_1"] = frame["kama"].pct_change()
    frame["kama_slope_3"] = frame["kama"].pct_change(3) / 3
    frame["price_vs_kama"] = close / frame["kama"] - 1

    atr_period = int(cfg.get("atr_period", 14))
    previous_close = close.shift(1)
    true_range = pd.concat(
        [high - low, (high - previous_close).abs(), (low - previous_close).abs()], axis=1
    ).max(axis=1)
    frame["atr"] = true_range.ewm(alpha=1 / atr_period, adjust=False, min_periods=atr_period).mean()
    frame["atr_pct"] = frame["atr"] / close
    frame["atr_z_72"] = _rolling_zscore(frame["atr_pct"], 72)

    adx_period = int(cfg.get("adx_period", 14))
    plus_dm = high.diff().where((high.diff() > -low.diff()) & (high.diff() > 0), 0.0)
    minus_dm = (-low.diff()).where((-low.diff() > high.diff()) & (-low.diff() > 0), 0.0)
    atr_wilder = true_range.ewm(alpha=1 / adx_period, adjust=False, min_periods=adx_period).mean()
    plus_di = 100 * plus_dm.ewm(alpha=1 / adx_period, adjust=False, min_periods=adx_period).mean() / atr_wilder
    minus_di = 100 * minus_dm.ewm(alpha=1 / adx_period, adjust=False, min_periods=adx_period).mean() / atr_wilder
    dx = 100 * (plus_di - minus_di).abs() / (plus_di + minus_di).replace(0, np.nan)
    frame["plus_di"] = plus_di
    frame["minus_di"] = minus_di
    frame["adx"] = dx.ewm(alpha=1 / adx_period, adjust=False, min_periods=adx_period).mean()
    frame["di_spread"] = (plus_di - minus_di) / 100

    donchian_period = int(cfg.get("donchian_period", 20))
    frame["donchian_high"] = high.shift(1).rolling(donchian_period).max()
    frame["donchian_low"] = low.shift(1).rolling(donchian_period).min()
    frame["donchian_mid"] = (frame["donchian_high"] + frame["donchian_low"]) / 2
    frame["donchian_position"] = (
        (close - frame["donchian_low"])
        / (frame["donchian_high"] - frame["donchian_low"]).replace(0, np.nan)
    )
    frame["donchian_width_pct"] = (frame["donchian_high"] - frame["donchian_low"]) / close

    bb_period = int(cfg.get("bollinger_period", 20))
    bb_std = float(cfg.get("bollinger_std", 2.0))
    bb_mid = close.rolling(bb_period).mean()
    bb_sigma = close.rolling(bb_period).std(ddof=0)
    frame["bb_mid"] = bb_mid
    frame["bb_upper"] = bb_mid + bb_std * bb_sigma
    frame["bb_lower"] = bb_mid - bb_std * bb_sigma
    frame["bb_width"] = (frame["bb_upper"] - frame["bb_lower"]) / bb_mid
    squeeze_lookback = int(cfg.get("squeeze_lookback", 120))
    frame["bb_width_percentile"] = frame["bb_width"].rolling(squeeze_lookback).apply(
        _last_percentile_rank, raw=True
    )

    rsi_period = int(cfg.get("rsi_period", 14))
    delta = close.diff()
    gains = delta.clip(lower=0).ewm(alpha=1 / rsi_period, adjust=False, min_periods=rsi_period).mean()
    losses = (-delta.clip(upper=0)).ewm(alpha=1 / rsi_period, adjust=False, min_periods=rsi_period).mean()
    rs = gains / losses.replace(0, np.nan)
    frame["rsi14"] = 100 - (100 / (1 + rs))
    frame["rsi_centered"] = (frame["rsi14"] - 50) / 50

    # --- Price, volume and time features ---
    for lookback in (1, 2, 3, 6, 12, 24, 48, 72):
        frame[f"return_{lookback}"] = close.pct_change(lookback)
    log_return = np.log(close).diff()
    frame["log_return_1"] = log_return
    for lookback in (3, 6, 12, 24, 48, 72):
        frame[f"realized_vol_{lookback}"] = log_return.rolling(lookback).std() * np.sqrt(lookback)

    frame["range_pct"] = (high - low) / close
    frame["body_pct"] = (close - open_) / open_
    frame["body_atr"] = (close - open_) / frame["atr"]
    frame["upper_wick_pct"] = (high - frame[["open", "close"]].max(axis=1)) / close
    frame["lower_wick_pct"] = (frame[["open", "close"]].min(axis=1) - low) / close
    frame["close_location"] = (close - low) / (high - low).replace(0, np.nan)

    volume_log = np.log1p(frame["volume"])
    frame["volume_change_1"] = volume_log.diff()
    frame["volume_z_24"] = _rolling_zscore(volume_log, 24)
    frame["volume_z_72"] = _rolling_zscore(volume_log, 72)
    if "quote_volume" in frame:
        frame["quote_volume_z_24"] = _rolling_zscore(np.log1p(frame["quote_volume"]), 24)
    else:
        frame["quote_volume_z_24"] = 0.0
    if "trades" in frame:
        frame["trades_z_24"] = _rolling_zscore(np.log1p(frame["trades"].fillna(0)), 24)
    else:
        frame["trades_z_24"] = 0.0

    hours = frame["open_time"].dt.hour
    weekdays = frame["open_time"].dt.dayofweek
    frame["hour_sin"] = np.sin(2 * np.pi * hours / 24)
    frame["hour_cos"] = np.cos(2 * np.pi * hours / 24)
    frame["weekday_sin"] = np.sin(2 * np.pi * weekdays / 7)
    frame["weekday_cos"] = np.cos(2 * np.pi * weekdays / 7)

    # --- Regime and independent event generation ---
    trend_adx = float(cfg.get("trend_adx_threshold", 18.0))
    up_regime = (close > frame["kama"]) & (frame["kama_slope_3"] > 0) & (frame["adx"] >= trend_adx)
    down_regime = (close < frame["kama"]) & (frame["kama_slope_3"] < 0) & (frame["adx"] >= trend_adx)
    frame["regime_code"] = np.select([up_regime, down_regime], [1, -1], default=0).astype(int)
    frame["regime"] = np.select(
        [up_regime, down_regime, frame["bb_width_percentile"] <= float(cfg.get("squeeze_percentile", 0.20))],
        ["TREND_UP", "TREND_DOWN", "COMPRESSION"],
        default="RANGE",
    )

    min_breakout_volume_z = float(cfg.get("breakout_min_volume_z", -0.25))
    breakout_up = (close > frame["donchian_high"]) & (frame["volume_z_24"] >= min_breakout_volume_z)
    breakout_down = (close < frame["donchian_low"]) & (frame["volume_z_24"] >= min_breakout_volume_z)

    squeeze_threshold = float(cfg.get("squeeze_percentile", 0.20))
    was_squeezed = frame["bb_width_percentile"].shift(1) <= squeeze_threshold
    squeeze_up = was_squeezed & (close > frame["bb_upper"]) & (frame["body_pct"] > 0)
    squeeze_down = was_squeezed & (close < frame["bb_lower"]) & (frame["body_pct"] < 0)

    pullback_tolerance_atr = float(cfg.get("pullback_tolerance_atr", 0.35))
    previous_near_kama = (close.shift(1) - frame["kama"].shift(1)).abs() <= (
        pullback_tolerance_atr * frame["atr"].shift(1)
    )
    pullback_up = (
        up_regime
        & previous_near_kama
        & (close > high.shift(1))
        & (frame["body_pct"] > 0)
    )
    pullback_down = (
        down_regime
        & previous_near_kama
        & (close < low.shift(1))
        & (frame["body_pct"] < 0)
    )

    impulse_atr = float(cfg.get("impulse_body_atr", 1.0))
    impulse_volume_z = float(cfg.get("impulse_min_volume_z", 0.50))
    impulse_up = (frame["body_atr"] >= impulse_atr) & (frame["volume_z_24"] >= impulse_volume_z)
    impulse_down = (frame["body_atr"] <= -impulse_atr) & (frame["volume_z_24"] >= impulse_volume_z)

    raw_event_type = np.select(
        [
            breakout_up | breakout_down,
            squeeze_up | squeeze_down,
            pullback_up | pullback_down,
            impulse_up | impulse_down,
        ],
        ["DONCHIAN_BREAKOUT", "SQUEEZE_RELEASE", "PULLBACK_RESUME", "VOLUME_IMPULSE"],
        default="NONE",
    )
    raw_event_direction = np.select(
        [breakout_up | squeeze_up | pullback_up | impulse_up, breakout_down | squeeze_down | pullback_down | impulse_down],
        [1, -1],
        default=0,
    ).astype(int)
    raw_score = (
        np.clip(frame["adx"].fillna(0) / 40, 0, 1)
        + np.clip(frame["volume_z_24"].fillna(0) / 3, -0.25, 1)
        + np.clip(frame["body_atr"].abs().fillna(0) / 2, 0, 1)
    ) / 3

    event_type, event_direction, event_id, event_score = _deduplicate_events(
        frame["open_time"], raw_event_type, raw_event_direction, raw_score,
        cooldown_hours=int(cfg.get("event_cooldown_hours", 3)),
    )
    frame["event_type"] = event_type
    frame["event_direction"] = event_direction
    frame["event_id"] = event_id
    frame["event_score"] = event_score
    frame["is_event"] = (frame["event_direction"] != 0).astype(int)
    frame["event_continuation_bias"] = frame["event_direction"] * frame["regime_code"]

    bars_since_event: list[float] = []
    active_event_direction: list[int] = []
    last_idx: int | None = None
    last_direction = 0
    for idx, direction in enumerate(frame["event_direction"].astype(int).tolist()):
        if direction != 0:
            last_idx = idx
            last_direction = direction
        bars_since_event.append(np.nan if last_idx is None else float(idx - last_idx))
        active_event_direction.append(last_direction)
    frame["bars_since_event"] = bars_since_event
    frame["active_event_direction"] = active_event_direction

    # News is available only at the first hourly boundary after both publication and collection.
    news_features = aggregate_news_hourly(news, frame["open_time"], settings)
    frame = frame.merge(news_features, on="open_time", how="left")
    news_cols = [col for col in frame.columns if col.startswith("news_")]
    frame[news_cols] = frame[news_cols].fillna(0.0)
    frame["news_shock"] = (
        (frame.get("news_count_1h", 0) >= float(cfg.get("news_shock_min_count", 3)))
        & (frame.get("news_relevance_3h", 0) >= float(cfg.get("news_shock_min_relevance", 0.55)))
    ).astype(int)

    if include_labels:
        _attach_labels(frame, horizons, strategy_cfg)

    excluded = {
        "provider", "symbol", "open_time", "fetched_at", "closed", "open", "high", "low", "close",
        "event_id", "event_type", "regime", "kama", "donchian_high", "donchian_low", "donchian_mid",
        "bb_mid", "bb_upper", "bb_lower", "atr",
    }
    for horizon in horizons:
        excluded.update(
            {
                f"entry_price_h{horizon}", f"future_return_h{horizon}", f"target_up_h{horizon}",
                f"mfe_h{horizon}", f"mae_h{horizon}", f"barrier_outcome_h{horizon}",
                f"event_continuation_h{horizon}", f"tradeable_h{horizon}",
                f"event_gross_return_h{horizon}", f"event_net_return_h{horizon}",
            }
        )
    feature_columns = [
        col for col in frame.columns
        if col not in excluded and pd.api.types.is_numeric_dtype(frame[col])
    ]
    frame = frame.replace([np.inf, -np.inf], np.nan)
    return FeatureSet(frame=frame, feature_columns=feature_columns, horizons=horizons)


def _attach_labels(frame: pd.DataFrame, horizons: list[int], strategy_cfg: dict[str, Any]) -> None:
    costs = execution_cost_breakdown(strategy_cfg)
    base_cost = costs["base_cost_bps"] / 10_000
    profit_buffer = costs["profit_buffer_bps"] / 10_000
    target_atr = float(strategy_cfg.get("label_target_atr_multiplier", 1.35))
    stop_atr = float(strategy_cfg.get("label_stop_atr_multiplier", 1.0))

    for horizon in horizons:
        entry = frame["open"].shift(-1)
        future_close = frame["close"].shift(-horizon)
        raw_return = future_close / entry - 1
        frame[f"entry_price_h{horizon}"] = entry
        frame[f"future_return_h{horizon}"] = raw_return
        frame[f"target_up_h{horizon}"] = (raw_return > 0).astype(float)
        frame.loc[raw_return.isna(), f"target_up_h{horizon}"] = np.nan

        mfe, mae, barrier = _path_labels(frame, horizon, target_atr, stop_atr)
        frame[f"mfe_h{horizon}"] = mfe
        frame[f"mae_h{horizon}"] = mae
        frame[f"barrier_outcome_h{horizon}"] = barrier

        event_direction = frame["event_direction"].astype(float)
        close_horizon_gross = event_direction * raw_return
        atr_move = frame["atr"] / entry
        # Path-aware realized gross return: target/stop first when touched, otherwise time-barrier close.
        event_gross = close_horizon_gross.copy()
        event_gross = event_gross.where(barrier != 1, target_atr * atr_move)
        event_gross = event_gross.where(barrier != -1, -stop_atr * atr_move)
        event_net = event_gross - base_cost
        continuation = (event_gross > 0).astype(float)
        # Tradeability is event-direction and execution-path aware.
        tradeable = (event_net >= profit_buffer).astype(float)
        non_event_or_missing = (event_direction == 0) | raw_return.isna() | pd.isna(barrier)
        continuation[non_event_or_missing] = np.nan
        tradeable[non_event_or_missing] = np.nan
        event_gross[non_event_or_missing] = np.nan
        event_net[non_event_or_missing] = np.nan
        frame[f"event_gross_return_h{horizon}"] = event_gross
        frame[f"event_net_return_h{horizon}"] = event_net
        frame[f"event_continuation_h{horizon}"] = continuation
        frame[f"tradeable_h{horizon}"] = tradeable


def _path_labels(
    frame: pd.DataFrame,
    horizon: int,
    target_atr_multiplier: float,
    stop_atr_multiplier: float,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    n = len(frame)
    mfe = np.full(n, np.nan)
    mae = np.full(n, np.nan)
    barrier = np.full(n, np.nan)
    for idx in range(n - horizon):
        direction = int(frame.iloc[idx]["event_direction"])
        if direction == 0:
            continue
        entry = float(frame.iloc[idx + 1]["open"])
        atr = float(frame.iloc[idx]["atr"])
        if not np.isfinite(entry) or not np.isfinite(atr) or entry <= 0 or atr <= 0:
            continue
        highs = frame.iloc[idx + 1 : idx + horizon + 1]["high"].to_numpy(dtype=float)
        lows = frame.iloc[idx + 1 : idx + horizon + 1]["low"].to_numpy(dtype=float)
        if direction > 0:
            favorable = highs / entry - 1
            adverse = entry / lows - 1
            target_price = entry + target_atr_multiplier * atr
            stop_price = entry - stop_atr_multiplier * atr
            target_hits = highs >= target_price
            stop_hits = lows <= stop_price
        else:
            favorable = entry / lows - 1
            adverse = highs / entry - 1
            target_price = entry - target_atr_multiplier * atr
            stop_price = entry + stop_atr_multiplier * atr
            target_hits = lows <= target_price
            stop_hits = highs >= stop_price
        mfe[idx] = float(np.nanmax(favorable))
        mae[idx] = float(np.nanmax(adverse))
        outcome = 0.0
        for bar_idx in range(len(highs)):
            target_hit = bool(target_hits[bar_idx])
            stop_hit = bool(stop_hits[bar_idx])
            # When both are touched inside one OHLC candle, use the conservative stop-first assumption.
            if stop_hit:
                outcome = -1.0
                break
            if target_hit:
                outcome = 1.0
                break
        barrier[idx] = outcome
    return mfe, mae, barrier


def aggregate_news_hourly(news: pd.DataFrame, candle_times: pd.Series, settings: Settings) -> pd.DataFrame:
    open_times = pd.to_datetime(candle_times, utc=True)
    decision_times = pd.DatetimeIndex(open_times + pd.Timedelta(hours=1), name="decision_time")
    base = pd.DataFrame(index=decision_times)
    windows = [int(x) for x in settings.section("features").get("news_windows_hours", [1, 3, 6, 12, 24])]
    if news.empty:
        for window in windows:
            for suffix in ("count", "sent_mean", "sent_sum", "weighted_sent", "relevance", "negative_share"):
                base[f"news_{suffix}_{window}h"] = 0.0
        base["news_age_hours"] = 999.0
        base["news_available"] = 0.0
        base["open_time"] = open_times.to_numpy()
        return base.reset_index(drop=True)

    articles = news.copy()
    articles["published_at"] = pd.to_datetime(articles["published_at"], utc=True)
    if "first_seen_at" in articles:
        articles["first_seen_at"] = pd.to_datetime(articles["first_seen_at"], utc=True)
        articles["available_at"] = articles[["published_at", "first_seen_at"]].max(axis=1)
    else:
        articles["available_at"] = articles["published_at"]
    articles["sentiment"] = pd.to_numeric(articles["sentiment"], errors="coerce").fillna(0.0)
    articles["relevance"] = pd.to_numeric(articles["relevance"], errors="coerce").fillna(0.0)
    articles = articles.sort_values("available_at")
    articles["decision_time"] = articles["available_at"].dt.ceil("h")
    articles["weighted_sent"] = articles["sentiment"] * (0.25 + articles["relevance"])
    articles["negative"] = (articles["sentiment"] < -0.25).astype(float)
    hourly = articles.groupby("decision_time").agg(
        count=("sentiment", "size"), sent_sum=("sentiment", "sum"),
        weighted_sum=("weighted_sent", "sum"), relevance_sum=("relevance", "sum"),
        negative_count=("negative", "sum"),
    ).reindex(decision_times, fill_value=0.0)
    for window in windows:
        rolling = hourly.rolling(window=window, min_periods=1).sum()
        count = rolling["count"].replace(0, np.nan)
        base[f"news_count_{window}h"] = rolling["count"].astype(float)
        base[f"news_sent_sum_{window}h"] = rolling["sent_sum"].astype(float)
        base[f"news_sent_mean_{window}h"] = (rolling["sent_sum"] / count).fillna(0.0)
        base[f"news_weighted_sent_{window}h"] = (rolling["weighted_sum"] / count).fillna(0.0)
        base[f"news_relevance_{window}h"] = (rolling["relevance_sum"] / count).fillna(0.0)
        base[f"news_negative_share_{window}h"] = (rolling["negative_count"] / count).fillna(0.0)

    decision_frame = pd.DataFrame({"decision_time": decision_times}).sort_values("decision_time")
    latest = pd.merge_asof(
        decision_frame,
        articles[["available_at"]].sort_values("available_at"),
        left_on="decision_time",
        right_on="available_at",
        direction="backward",
    )
    age = (latest["decision_time"] - latest["available_at"]).dt.total_seconds().div(3600)
    base["news_age_hours"] = age.fillna(999.0).to_numpy()
    base["news_available"] = latest["available_at"].notna().astype(float).to_numpy()
    base["open_time"] = open_times.to_numpy()
    return base.reset_index(drop=True)


def sample_weights(frame: pd.DataFrame, settings: Settings) -> np.ndarray:
    cfg = settings.section("features")
    event_weight = float(cfg.get("event_sample_weight", 2.5))
    normal_weight = float(cfg.get("normal_sample_weight", 1.0))
    weights = np.where(frame["is_event"].to_numpy(dtype=bool), event_weight, normal_weight).astype(float)
    # Give recent history a mild, bounded emphasis without discarding older regimes.
    recency = np.linspace(float(cfg.get("oldest_sample_weight", 0.75)), 1.0, len(frame))
    return weights * recency


def _deduplicate_events(
    times: pd.Series,
    raw_types: np.ndarray,
    raw_directions: np.ndarray,
    raw_scores: pd.Series,
    cooldown_hours: int,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    n = len(times)
    event_type = np.full(n, "NONE", dtype=object)
    direction = np.zeros(n, dtype=int)
    event_id = np.full(n, None, dtype=object)
    score = np.zeros(n, dtype=float)
    last_index_by_direction: dict[int, int] = {}
    sequence = 0
    for idx in range(n):
        raw_direction = int(raw_directions[idx])
        raw_type = str(raw_types[idx])
        if raw_direction == 0 or raw_type == "NONE":
            continue
        last_idx = last_index_by_direction.get(raw_direction)
        if last_idx is not None and idx - last_idx <= cooldown_hours:
            continue
        sequence += 1
        event_type[idx] = raw_type
        direction[idx] = raw_direction
        timestamp = pd.Timestamp(times.iloc[idx]).strftime("%Y%m%dT%H%MZ")
        event_id[idx] = f"EV{sequence:05d}-{timestamp}-{raw_type}-{'UP' if raw_direction > 0 else 'DOWN'}"
        score[idx] = float(raw_scores.iloc[idx]) if np.isfinite(raw_scores.iloc[idx]) else 0.0
        last_index_by_direction[raw_direction] = idx
    return event_type, direction, event_id, score


def _kama(series: pd.Series, er_period: int, fast_period: int, slow_period: int) -> pd.Series:
    values = series.to_numpy(dtype=float)
    result = np.full(len(values), np.nan)
    change = series.diff(er_period).abs()
    volatility = series.diff().abs().rolling(er_period).sum()
    efficiency = (change / volatility.replace(0, np.nan)).clip(0, 1)
    fast_sc = 2 / (fast_period + 1)
    slow_sc = 2 / (slow_period + 1)
    smoothing = (efficiency * (fast_sc - slow_sc) + slow_sc) ** 2
    first = er_period
    if len(values) <= first:
        return pd.Series(result, index=series.index)
    result[first] = float(np.nanmean(values[: first + 1]))
    for idx in range(first + 1, len(values)):
        if not np.isfinite(values[idx]) or not np.isfinite(result[idx - 1]):
            continue
        sc = float(smoothing.iloc[idx]) if np.isfinite(smoothing.iloc[idx]) else slow_sc**2
        result[idx] = result[idx - 1] + sc * (values[idx] - result[idx - 1])
    return pd.Series(result, index=series.index)


def _rolling_zscore(series: pd.Series, window: int) -> pd.Series:
    mean = series.rolling(window).mean()
    std = series.rolling(window).std(ddof=0).replace(0, np.nan)
    return (series - mean) / std


def _last_percentile_rank(values: np.ndarray) -> float:
    if len(values) == 0 or not np.isfinite(values[-1]):
        return np.nan
    valid = values[np.isfinite(values)]
    if len(valid) == 0:
        return np.nan
    return float(np.mean(valid <= values[-1]))
